name: Lint & Format

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm
      - name: Install
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: Prettier (check)
        run: npm run format:check
